AWSTemplateFormatVersion: "2010-09-09"
Description: Named api-gateway-jwt-authorizer-poc-authorizer.
Resources:
  Authorizer:
    Type: "AWS::ApiGateway::Authorizer"
    Properties:
      AuthorizerResultTtlInSeconds: 300  # Default
      AuthorizerUri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:438053794079:function:api-gateway-jwt-authorizer/invocations
      IdentitySource: "method.request.header.Authorization"
      IdentityValidationExpression: "[a-zA-Z0-9\\-_]*"
      Name: "jwt"
      RestApiId: "so7o3tr66d"
      Type: "TOKEN"
  AllowApiGatewayInvokeFunction:  # Used by authorizerCredentials
    Type: AWS::IAM::Role
    Properties:
      RoleName: "api-gateway-invoke-jwt-authorizer"
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: "*"  # TODO least privilege
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
